name: Deploy to Cloud Run2

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: pr-sandboxapigee-alex
  SERVICE_NAME: helloworld-php
  REGION: europe-west1 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: gcloud auth configure-docker
        
        

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: eu.gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v0.3.0
        with:
          service_name: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image_uri: eu.gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          revision_name: ${{ github.sha }}
